---
abstract: 'Fast integer ID sequences with ElasticSearch'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  ElasticSearch: 0.46
  ElasticSearch::TestServer: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearchX-Sequence
requires:
  Carp: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/ElasticSearchX-Sequence/issues
  homepage: https://metacpan.org/module/ElasticSearchX::Sequence
  repository: git://github.com/clintongormley/ElasticSearchX-Sequence.git
version: 0.01
